name: Generate GitHub Stats SVG

on:
  schedule:
    - cron: "0 2 * * *"   # daily
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Stats SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Jayapramod
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Kolkata
          output_action: github-pages
          output_branch: output
          output_filename: github-stats.svg
